#!/usr/bin/env bash
#script that displays numbers from 1 to 20, 
#displays 4 and then bad luck from China
#displays 9 and then bad luck from Japan
#displays 17 and then bad luck from Italy

num=1

while [ $num -le 20 ]; do
case $num in
	4) echo "$num"; echo "bad luck from China"; ((num++)); continue;;
	9) echo "$num"; echo "bad luck from Japan"; ((num++)); continue;;
	17) echo "$num"; echo "bad luck from Italy"; ((num++)); continue;;
	*) echo "$num";;
esac
((num++))
done
